server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-vehicle
          uri: lb://ms-vehicle
          predicates:
            - Path=/vehicles/**
        - id: ms-repair_list
          uri: lb://ms-repair_list
          predicates:
            - Path=/repairs/**
        - id: ms-reports
          uri: lb://ms-reports
          predicates:
            - Path=/reports/**
        - id: ms-vehicle_repair
          uri: lb://ms-vehicle_repair
          predicates:
            - Path=/vehicle_repairs/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.handler: DEBUG
