server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-vehicle
          uri: lb://ms-vehicle
          predicates:
            - Path=/vehicles/**
        - id: static-ms-vehicle
          uri: http://localhost:8090
          predicates:
            - Path=/static-vehicles/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.handler: DEBUG
