server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/repair_list
    username: root
    password: brayito
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka