server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_repair
    username: root
    password: brayito
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka